services:
  html-go-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html-go-express
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - html-go-data:/usr/src/app/data
    env_file:
      - .env.production
    networks:
      - html-go-network

volumes:
  html-go-data:
    driver: local

networks:
  html-go-network:
    driver: bridge
